name: Scrape Inmate Data

on:
  # Run on a schedule (at 11:00 AM, 5:00 PM, and 11:00 PM UTC)
  schedule:
    - cron: '0 11,17,23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Run the scraper script
      - name: Run scraper
        run: python main.py

      # 5. Commit the updated database.json and newly_added.json files back to the repository
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add database.json newly_added.json
          # Check if there are changes to commit
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update inmate data" -a
          fi
      
      # 6. Push the changes back to the repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Or your default branch name
