name: Scrape Inmate Data

on:
  schedule:
    - cron: '0 11,17,23 * * *'
  workflow_dispatch:

# This is the new block that grants write permissions
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add database.json newly_added.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update inmate data" -a
          fi
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
